export const queryKeys = {
  activities: ["activities"] as const,
  automations: ["automations"] as const,
  automationRuns: ["automation-runs"] as const,
  campaigns: ["campaigns"] as const,
  contacts: ["contacts"] as const,
  conversations: ["conversations"] as const,
  dashboard: ["dashboard"] as const,
  inbox: ["inbox"] as const,
  inboxSearch: ["inbox-search"] as const,
  inboxThread: ["inbox-thread"] as const,
  labels: ["labels"] as const,
  logs: ["logs"] as const,
  webhookLogs: ["webhook-logs"] as const,
  media: ["media"] as const,
  messageStudio: ["message-studio"] as const,
  messages: ["messages"] as const,
  notes: ["notes"] as const,
  profile: ["profile"] as const,
  quickReplies: ["quick-replies"] as const,
  quotas: ["quotas"] as const,
  quotaForecast: ["quota-forecast"] as const,
  scheduledMessages: ["scheduled-messages"] as const,
  search: ["search"] as const,
  settings: ["settings"] as const,
  tasks: ["tasks"] as const,
  templates: ["templates"] as const,
  webhooks: ["webhooks"] as const,
  whatsappConnections: ["whatsapp-connections"] as const,
  workspaceMembers: ["workspace-members"] as const,
  pipelines: ["pipelines"] as const,
  stages: ["stages"] as const,
  deals: ["deals"] as const,
  views: ["views"] as const,
  products: ["products"] as const,
  product: (id: string) => ["products", id] as const,
  variants: (productId: string) => ["products", productId, "variants"] as const,
  variantSuppliers: (variantId: string) => ["variants", variantId, "suppliers"] as const,
  categories: ["categories"] as const,
  brands: ["brands"] as const,
  units: ["units"] as const,
  suppliers: ["suppliers"] as const,
  locations: ["locations"] as const,
  location: (id: string) => ["locations", id] as const,
  inventoryLevels: ["inventory-levels"] as const,
  inventoryLevel: (id: string) => ["inventory-levels", id] as const,
  inventoryItems: ["inventory-items"] as const,
  stockMovements: ["stock-movements"] as const,
  salesOrders: ["sales-orders"] as const,
  salesOrder: (id: string) => ["sales-orders", id] as const,
  quotes: ["quotes"] as const,
  invoices: ["invoices"] as const,
  invoice: (id: string) => ["invoices", id] as const,
  invoiceSettings: ["invoices", "settings"] as const,
  payments: ["payments"] as const,
  payment: (id: string) => ["payments", id] as const,
  invoicePayments: (invoiceId: string) => ["invoices", invoiceId, "payments"] as const,
  salesReturns: ["sales-returns"] as const,
  salesReturn: (id: string) => ["sales-returns", id] as const,
  orderReturns: (orderId: string) => ["sales-orders", orderId, "returns"] as const,
  orderReturnableQuantities: (orderId: string) => ["sales-orders", orderId, "returnable-quantities"] as const,
  currencies: ["sales", "currencies"] as const,
  purchaseOrders: ["purchase-orders"] as const,
  purchaseOrder: (id: string) => ["purchase-orders", id] as const,
  purchasingSummary: ["purchasing-summary"] as const,
  purchaseReturns: ["purchase-returns"] as const,
  purchaseReturn: (id: string) => ["purchase-returns", id] as const,
  finance: {
    accounts: ["finance", "accounts"] as const,
    account: (id: string) => ["finance", "accounts", id] as const,
    accountLedger: (id: string) => ["finance", "accounts", id, "ledger"] as const,
    taxConfigurations: ["finance", "tax-configurations"] as const,
    taxConfiguration: (id: string) => ["finance", "tax-configurations", id] as const,
    expenses: ["finance", "expenses"] as const,
    expense: (id: string) => ["finance", "expenses", id] as const,
    income: ["finance", "income"] as const,
    journals: ["finance", "journals"] as const,
    journal: (id: string) => ["finance", "journals", id] as const,
    receivables: ["finance", "receivables"] as const,
    receivablesAging: ["finance", "receivables", "aging"] as const,
    payables: ["finance", "payables"] as const,
    payablesAging: ["finance", "payables", "aging"] as const,
    reports: {
      trialBalance: (filter?: unknown) => ["finance", "reports", "trial-balance", filter] as const,
      profitAndLoss: (filter?: unknown) => ["finance", "reports", "profit-and-loss", filter] as const,
      balanceSheet: (filter?: unknown) => ["finance", "reports", "balance-sheet", filter] as const,
      cashFlow: (filter?: unknown) => ["finance", "reports", "cash-flow", filter] as const,
      taxSummary: (filter?: unknown) => ["finance", "reports", "tax-summary", filter] as const,
    },
    reconciliation: {
      receivables: (date?: string) => ["finance", "reconciliation", "receivables", date] as const,
      payables: (date?: string) => ["finance", "reconciliation", "payables", date] as const,
      bank: (accountId?: string, date?: string) => ["finance", "reconciliation", "bank", accountId, date] as const,
    },
    settings: ["finance", "settings"] as const,
  },
};

