export const queryKeys = {
  activities: ["activities"] as const,
  automations: ["automations"] as const,
  automationRuns: ["automation-runs"] as const,
  campaigns: ["campaigns"] as const,
  contacts: ["contacts"] as const,
  conversations: ["conversations"] as const,
  dashboard: ["dashboard"] as const,
  inbox: ["inbox"] as const,
  inboxSearch: ["inbox-search"] as const,
  inboxThread: ["inbox-thread"] as const,
  labels: ["labels"] as const,
  logs: ["logs"] as const,
  webhookLogs: ["webhook-logs"] as const,
  media: ["media"] as const,
  messageStudio: ["message-studio"] as const,
  messages: ["messages"] as const,
  notes: ["notes"] as const,
  profile: ["profile"] as const,
  quickReplies: ["quick-replies"] as const,
  quotas: ["quotas"] as const,
  quotaForecast: ["quota-forecast"] as const,
  scheduledMessages: ["scheduled-messages"] as const,
  search: ["search"] as const,
  settings: ["settings"] as const,
  tasks: ["tasks"] as const,
  templates: ["templates"] as const,
  webhooks: ["webhooks"] as const,
  whatsappConnections: ["whatsapp-connections"] as const,
  workspaceMembers: ["workspace-members"] as const,
  pipelines: ["pipelines"] as const,
  stages: ["stages"] as const,
  deals: ["deals"] as const,
  views: ["views"] as const,
  products: ["products"] as const,
  product: (id: string) => ["products", id] as const,
  variants: (productId: string) => ["products", productId, "variants"] as const,
  variantSuppliers: (variantId: string) => ["variants", variantId, "suppliers"] as const,
  categories: ["categories"] as const,
  brands: ["brands"] as const,
  units: ["units"] as const,
  suppliers: ["suppliers"] as const,
  locations: ["locations"] as const,
  location: (id: string) => ["locations", id] as const,
  inventoryLevels: ["inventory-levels"] as const,
  inventoryLevel: (id: string) => ["inventory-levels", id] as const,
  inventoryItems: ["inventory-items"] as const,
  stockMovements: ["stock-movements"] as const,
};
